#Simplified CI config
#Using docker-in-docker
image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - build
  - test

#Had to specify docker host to be able to run test to check if website is served
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

#Standard show docker info for reference
before_script:
  - docker info

#Build and create new tag (docker hub will auto build on new git push)
build:
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .

#Run two simple tests
test:
  stage: test
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - echo 'test starting'
    - sh test/test-produce.sh
    - sh test/test-serve.sh
    
    

